{
    "name": "Condominium Management",
    "summary": "Manage condominium properties and units ",
    "version": "18.0.1.0.1",
    "category": "Condominium",
    "author": "Wilfred Vásquez",
    "license": "LGPL-3",
    "installable": True,
    "application": True,
    "depends": ["base", "contacts", "portal", "mail"],
    "data": [
        "security/condominium.security.xml",
        "security/ir.model.access.csv",
        "wizards/add_default_service.xml",
        "views/condominium.xml",
        "views/property.xml",
        "views/bill.xml",
        "views/property_charge.xml",
        "views/service.xml",
        "views/property_previous_debt.xml",
        "views/menuitems.xml",
    ],
}
